sudo: required
branches:
  only:
  - master
before_script:
- sudo apt-get purge nodejs npm
- curl -sL https://deb.nodesource.com/setup_6.x | sudo bash -
- sudo apt-get install -y nodejs
- sudo npm install -g resume-cli@0.4.14
script:
- bash ./deploy.sh
env:
  global:
  - GH_REF: github.com/bengadbois/resume.git
a0ce826f9eeac3bc4918a4c227fe965b94e0f10f:
  secure: "DUOX10UkxAzMI0LstNtNkc93IdFkZQkuYJuRtt2n7O0GxZUjxyCN9VE5LYFhMZ1SK3kwzaU/stqLBiOU4KDH3YCffYBPGEpuSUuQPzeu9auTeJv9TOmJ2EBxaE9ZIcdUS6tgj8zOVCgs17gW3hxJS/JNlhI05POL+JQT9RTETZPMjjsjf3NhC3/MMtkSg45MouOaPaWb3eMiBC8DEo5zlf+Q6t/44wsWtbnkzVJfgRU8NDASCgNkunQUIqBBelTzwcpzmGGGHMjMb4CC2oFxP8aVinwspT6hb2r8VSm/owE1evP3xY0bOZhIVWKjkoIa8EYrLrL3X4AIdITVK2FzqqktkHOXhkjuH5Nv9bw7NWn8hypeTagImmB6lu/STeoB0Phb2ecTFWp9l58+6PolKuL6ykgHXsEIfPn8FnW2BMnuDuFi5FN9GzkUpWj2U6VTEzs41cSYVNsRYK1stUsBXMB0dFu6DIKZHjS60LG3A6g+xeFZkjru3dn6pFMkGOUW0S62vVMKvmQQjCP3qElDwHvOVb5inzamG+xIq9025V2SBEJ7gNZ2+hvpUDODRnpnEbLnEoFFza629vY6bSrT7GwQGx7kXRcRSOUVDG7uiW4IJHxGli6x7oe66Dv+ujel0zl7iClWpcAFdvKOEi94bcU5JIWeLJoCuAKj2xS4dzM="
